# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ata_piix" "uhci_hcd" "virtio_pci" "virtio_scsi" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-label/NIXROOT";
      fsType = "ext4";
    };

  fileSystems."/mnt/pve" =
    { device = "/dev/disk/by-uuid/63f9bccd-80c6-46a6-95e0-b8a55884de94";
      fsType = "ext4";
    };


  swapDevices = [ {
    device = "/swapfile";
    size = 2048;
    priority = -1;
  } ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
